### ISSUE TITLE
CORS "Access Denied" error in Internet Explorer 11 when loading CSS file from remote server

### ISSUE THREAD

**Issue by cormip** [dolox/fallback#18]
I'm only seeing this problem in Internet Explorer 11. (Haven't tested IE9 or IE10.)

Using fallback.js version 1.1.1, error occurs on Line 208:

if (stylesheet.rules) {

in function fallback.css.check()

Test page exhibiting the problem (IE11) is here:

http://win-soft.s3.amazonaws.com/public/fallback-test.html

**Comment by sgarbesi** [comment]
@cormip I noticed this a few days ago in Firefox as well. Not sure if it's something new or what the case is; as I know this did work in Firefox at one time.

http://stackoverflow.com/questions/5323604/firefox-not-able-to-enumerate-document-stylesheets-cssrules

I just submitted a patch for the bug in revision 1.1.2. Can you try that and let me know if it works for you?

PS: Looking to release version 2.0 soon which will come with a full unit test suite so hopefully things like this will popup faster when newer browser versions are released that contain breaking changes for the library.

**Comment by sgarbesi** [comment]
Closing as 1.1.2 looks to have resolved the issue.

**Comment by cormip** [comment]
Yes, it appears to be fixed. Thanks.

**Comment by MrJamesEllis** [comment]
Just stumbled across this. In IE11/Win7 am getting "access is denied" for the demo URL provided in the initial comment - in the fallback.js it's loading the error is on line 212 column 4 "if(stylesheet.rules) ......"

Weird thing is hitting enter/return after placing the cursor at the end of the URL in the address bar gets the "All Loaded". Hitting the refresh button in the browser, the page sticks on "Loading..."

**Comment by sgarbesi** [comment]
@civkati Update the library,

**Comment by MrJamesEllis** [comment]
Hi, the library being used is the one linked to on the original comment - http://rawgithub.com/dolox/fallback/master/fallback.js which is marked as "fallback.js v1.1.4"

I've got the same issue on another site with IE (all versions) and it only seems to affect external stylesheet loading

The workaround was to load the stylesheets the classic way.
The reasoning for loading the external stylesheets (font awesome, google fonts) is that they have no bearing on the layout and of the page and so can be loaded with fallback to avoid render blocking (noted in Pagespeed reports and documentation).

Hope that helps.. although not sure of the workaround but any more info required pls ask.

Edit: possibly similar to this issue in respond.js:

https://github.com/scottjehl/Respond/issues/5#issuecomment-786991
https://github.com/scottjehl/Respond/issues/6

**Comment by sgarbesi** [comment]
@civkati I'll take a look tomorrow. What version of IE11 are you on? Microsoft must've updated/changed something as @cormip and I both confirmed that this was fixed by testing in IE11.

**Comment by MrJamesEllis** [comment]
![image](https://cloud.githubusercontent.com/assets/603960/4314379/301a41e4-3ede-11e4-82a2-5ecd670f6996.png)

Here's a screen of the error.

**Comment by dylanparry** [comment]
I’m also seeing this error in IE11 (currently using 11.0.9600.17278). I’m attempting to load Font Awesome and Bootstrap CSS from a CDN, with a local fallback—and as civkati says, it’s only the external stylesheets causing the problem, so for now I’m simply commenting them out and letting it use the fallback every time.

Any progress on finding out what is causing it, or figuring out how to fix it?

**Comment by sgarbesi** [comment]
@dylanparry Can you supply a plnkr demo?

**Comment by dylanparry** [comment]
Sure. I’ve set up a really basic example at http://plnkr.co/aMjuPtA8XGHEzBwXTIqj/.

It only attempts to load in the external CSS, without the local fallback, and doesn’t have anything of substance in the HTML. It still fails, as expected in IE11, but works in other browsers.

**Comment by sgarbesi** [comment]
@cormip @civkati @dylanparry Please test v1.1.5

**Comment by dylanparry** [comment]
It sort of works—the CDN version will now load, but if the CDN fails to load then the fallback stylesheets aren’t added to the document, so I get an unstyled document.

I’ve updated the plnkr example to load a fallback:

http://plnkr.co/aMjuPtA8XGHEzBwXTIqj

and here’s a version where the CDN is a bad URL so won’t ever load:

http://plnkr.co/g77iBUFFkBrUqQONY8ZF

In IE11 it fails to load the fallback CSS on the second example, Seems to work fine in other browsers though.

**Comment by sgarbesi** [comment]
@cormip @civkati @dylanparry Upgrade to v1.1.6

http://plnkr.co/edit/bBTQTX3WT3k3uNaDNWSH?p=streamer

Working demo that I tested in IE11.

Please confirm.

Apparently IE always fires an `onload` no matter whether it's successful or not for link elements. I had to add a CSS style check, only added it for IE11

Gotta love IE, it will keep us all in business forever.

**Comment by dylanparry** [comment]
A quick test confirmed it now works for me. Thanks :)
